# Generated by Django 2.1.5 on 2019-02-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tweet',
            field=models.URLField(unique='true'),
        ),
    ]
