# Generated by Django 2.1.5 on 2019-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190206_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tweet',
            field=models.URLField(),
        ),
    ]
